# fly.toml app configuration file generated for clip-it on 2025-06-06T07:42:42-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'clip-it'
primary_region = 'sjc'

[build]
  dockerfile = 'Dockerfile'

[env]
  PORT = '8080'
  PYTHONUNBUFFERED = '1'

[[mounts]]
  source = 'clip_it_data'
  destination = '/app/snippets'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 2
