app = "clip-it"
primary_region = "sjc"

[build]
  [build.args]
    PYTHON_VERSION = "3.11"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[mounts]
  source="clip_it_data"
  destination="/app/snippets"

[[vm]]
  memory = "2gb"
  cpu_kind = "shared"
  cpus = 2